from typing import List
import ghidra.framework.plugintool.util
import java.lang
import java.util
import org.jdom


class PluginClassManager(object):




    def __init__(self, filterClass: java.lang.Class, exclusionClass: java.lang.Class): ...



    def addXmlElementsForPlugins(self, __a0: org.jdom.Element, __a1: List[object]) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def fillInPackageClasses(self, __a0: List[object]) -> java.util.Set: ...

    def getClass(self) -> java.lang.Class: ...

    def getManagedPluginDescriptions(self) -> List[ghidra.framework.plugintool.util.PluginDescription]: ...

    def getPluginClasses(self, element: org.jdom.Element) -> java.util.Set: ...

    def getPluginDescription(self, className: unicode) -> ghidra.framework.plugintool.util.PluginDescription: ...

    def getPluginDescriptions(self, pluginPackage: ghidra.framework.plugintool.util.PluginPackage) -> List[ghidra.framework.plugintool.util.PluginDescription]: ...

    def getPluginPackages(self) -> List[ghidra.framework.plugintool.util.PluginPackage]: ...

    def getUnstablePluginDescriptions(self) -> List[ghidra.framework.plugintool.util.PluginDescription]: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def managedPluginDescriptions(self) -> List[object]: ...

    @property
    def pluginPackages(self) -> List[object]: ...

    @property
    def unstablePluginDescriptions(self) -> List[object]: ...