# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechly/slu/v1/batch_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from speechly.slu.v1 import batch_pb2 as speechly_dot_slu_dot_v1_dot_batch__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fspeechly/slu/v1/batch_api.proto\x12\x0fspeechly.slu.v1\x1a\x1bspeechly/slu/v1/batch.proto\"\xe6\x02\n\x13ProcessAudioRequest\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x08 \x01(\t\x12\x33\n\x06\x63onfig\x18\x02 \x01(\x0b\x32#.speechly.slu.v1.AudioConfiguration\x12\x0f\n\x05\x61udio\x18\x03 \x01(\x0cH\x00\x12\r\n\x03uri\x18\x04 \x01(\tH\x00\x12\x34\n\x0bhttp_source\x18\t \x01(\x0b\x32\x1d.speechly.slu.v1.HttpResourceH\x00\x12\x15\n\x0bresults_uri\x18\x05 \x01(\tH\x01\x12\x34\n\x0bhttp_result\x18\n \x01(\x0b\x32\x1d.speechly.slu.v1.HttpResourceH\x01\x12\x11\n\treference\x18\x06 \x01(\t\x12(\n\x07options\x18\x07 \x03(\x0b\x32\x17.speechly.slu.v1.OptionB\x08\n\x06sourceB\r\n\x0b\x64\x65stination\"E\n\x14ProcessAudioResponse\x12-\n\toperation\x18\x01 \x01(\x0b\x32\x1a.speechly.slu.v1.Operation\"3\n\x12QueryStatusRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\treference\x18\x02 \x01(\t\"D\n\x13QueryStatusResponse\x12-\n\toperation\x18\x01 \x01(\x0b\x32\x1a.speechly.slu.v1.Operation2\xc3\x01\n\x08\x42\x61tchAPI\x12]\n\x0cProcessAudio\x12$.speechly.slu.v1.ProcessAudioRequest\x1a%.speechly.slu.v1.ProcessAudioResponse(\x01\x12X\n\x0bQueryStatus\x12#.speechly.slu.v1.QueryStatusRequest\x1a$.speechly.slu.v1.QueryStatusResponseBg\n\x13\x63om.speechly.slu.v1B\rBatchApiProtoP\x01Z\x15speechly/slu/v1;sluv1\xa2\x02\x03SSX\xaa\x02\x0fSpeechly.Slu.V1\xca\x02\x0fSpeechly\\Slu\\V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speechly.slu.v1.batch_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023com.speechly.slu.v1B\rBatchApiProtoP\001Z\025speechly/slu/v1;sluv1\242\002\003SSX\252\002\017Speechly.Slu.V1\312\002\017Speechly\\Slu\\V1'
  _globals['_PROCESSAUDIOREQUEST']._serialized_start=82
  _globals['_PROCESSAUDIOREQUEST']._serialized_end=440
  _globals['_PROCESSAUDIORESPONSE']._serialized_start=442
  _globals['_PROCESSAUDIORESPONSE']._serialized_end=511
  _globals['_QUERYSTATUSREQUEST']._serialized_start=513
  _globals['_QUERYSTATUSREQUEST']._serialized_end=564
  _globals['_QUERYSTATUSRESPONSE']._serialized_start=566
  _globals['_QUERYSTATUSRESPONSE']._serialized_end=634
  _globals['_BATCHAPI']._serialized_start=637
  _globals['_BATCHAPI']._serialized_end=832
# @@protoc_insertion_point(module_scope)
