# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechly/slu/v1/wlu.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19speechly/slu/v1/wlu.proto\x12\x0fspeechly.slu.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n\x0cTextsRequest\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12-\n\x08requests\x18\x02 \x03(\x0b\x32\x1b.speechly.slu.v1.WLURequest\"@\n\rTextsResponse\x12/\n\tresponses\x18\x01 \x03(\x0b\x32\x1c.speechly.slu.v1.WLUResponse\"e\n\nWLURequest\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x32\n\x0ereference_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"<\n\x0bWLUResponse\x12-\n\x08segments\x18\x01 \x03(\x0b\x32\x1b.speechly.slu.v1.WLUSegment\"\xb7\x01\n\nWLUSegment\x12\x0c\n\x04text\x18\x01 \x01(\t\x12)\n\x06tokens\x18\x02 \x03(\x0b\x32\x19.speechly.slu.v1.WLUToken\x12,\n\x08\x65ntities\x18\x03 \x03(\x0b\x32\x1a.speechly.slu.v1.WLUEntity\x12*\n\x06intent\x18\x04 \x01(\x0b\x32\x1a.speechly.slu.v1.WLUIntent\x12\x16\n\x0e\x61nnotated_text\x18\x05 \x01(\t\"\'\n\x08WLUToken\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\"X\n\tWLUEntity\x12\x0e\n\x06\x65ntity\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x16\n\x0estart_position\x18\x03 \x01(\x05\x12\x14\n\x0c\x65nd_position\x18\x04 \x01(\x05\"\x1b\n\tWLUIntent\x12\x0e\n\x06intent\x18\x01 \x01(\t2\x90\x01\n\x03WLU\x12\x41\n\x04Text\x12\x1b.speechly.slu.v1.WLURequest\x1a\x1c.speechly.slu.v1.WLUResponse\x12\x46\n\x05Texts\x12\x1d.speechly.slu.v1.TextsRequest\x1a\x1e.speechly.slu.v1.TextsResponseBb\n\x13\x63om.speechly.slu.v1B\x08WluProtoP\x01Z\x15speechly/slu/v1;sluv1\xa2\x02\x03SSX\xaa\x02\x0fSpeechly.Slu.V1\xca\x02\x0fSpeechly\\Slu\\V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speechly.slu.v1.wlu_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023com.speechly.slu.v1B\010WluProtoP\001Z\025speechly/slu/v1;sluv1\242\002\003SSX\252\002\017Speechly.Slu.V1\312\002\017Speechly\\Slu\\V1'
  _globals['_TEXTSREQUEST']._serialized_start=79
  _globals['_TEXTSREQUEST']._serialized_end=156
  _globals['_TEXTSRESPONSE']._serialized_start=158
  _globals['_TEXTSRESPONSE']._serialized_end=222
  _globals['_WLUREQUEST']._serialized_start=224
  _globals['_WLUREQUEST']._serialized_end=325
  _globals['_WLURESPONSE']._serialized_start=327
  _globals['_WLURESPONSE']._serialized_end=387
  _globals['_WLUSEGMENT']._serialized_start=390
  _globals['_WLUSEGMENT']._serialized_end=573
  _globals['_WLUTOKEN']._serialized_start=575
  _globals['_WLUTOKEN']._serialized_end=614
  _globals['_WLUENTITY']._serialized_start=616
  _globals['_WLUENTITY']._serialized_end=704
  _globals['_WLUINTENT']._serialized_start=706
  _globals['_WLUINTENT']._serialized_end=733
  _globals['_WLU']._serialized_start=736
  _globals['_WLU']._serialized_end=880
# @@protoc_insertion_point(module_scope)
