
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-31T14:56:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "926ca40348b06a49b520aa26eea37a5a3de59884",
 "version": "2.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
