
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-29T16:40:22+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7cceee90e6e1dfe2d0870907f193ba4c99d71212",
 "version": "5.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
