# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = ['ExternalNetworkArgs', 'ExternalNetwork']

@pulumi.input_type
class ExternalNetworkArgs:
    def __init__(__self__, *,
                 cloudspace_id: pulumi.Input[str],
                 customer_id: pulumi.Input[str],
                 external_network_id: pulumi.Input[str],
                 external_network_ip: pulumi.Input[str],
                 external_network_type: pulumi.Input[str],
                 metric: pulumi.Input[int],
                 token: pulumi.Input[str],
                 url: pulumi.Input[str]):
        """
        The set of arguments for constructing a ExternalNetwork resource.
        """
        pulumi.set(__self__, "cloudspace_id", cloudspace_id)
        pulumi.set(__self__, "customer_id", customer_id)
        pulumi.set(__self__, "external_network_id", external_network_id)
        pulumi.set(__self__, "external_network_ip", external_network_ip)
        pulumi.set(__self__, "external_network_type", external_network_type)
        pulumi.set(__self__, "metric", metric)
        pulumi.set(__self__, "token", token)
        pulumi.set(__self__, "url", url)

    @property
    @pulumi.getter
    def cloudspace_id(self) -> pulumi.Input[str]:
        return pulumi.get(self, "cloudspace_id")

    @cloudspace_id.setter
    def cloudspace_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "cloudspace_id", value)

    @property
    @pulumi.getter(name="customerID")
    def customer_id(self) -> pulumi.Input[str]:
        return pulumi.get(self, "customer_id")

    @customer_id.setter
    def customer_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "customer_id", value)

    @property
    @pulumi.getter
    def external_network_id(self) -> pulumi.Input[str]:
        return pulumi.get(self, "external_network_id")

    @external_network_id.setter
    def external_network_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "external_network_id", value)

    @property
    @pulumi.getter
    def external_network_ip(self) -> pulumi.Input[str]:
        return pulumi.get(self, "external_network_ip")

    @external_network_ip.setter
    def external_network_ip(self, value: pulumi.Input[str]):
        pulumi.set(self, "external_network_ip", value)

    @property
    @pulumi.getter
    def external_network_type(self) -> pulumi.Input[str]:
        return pulumi.get(self, "external_network_type")

    @external_network_type.setter
    def external_network_type(self, value: pulumi.Input[str]):
        pulumi.set(self, "external_network_type", value)

    @property
    @pulumi.getter
    def metric(self) -> pulumi.Input[int]:
        return pulumi.get(self, "metric")

    @metric.setter
    def metric(self, value: pulumi.Input[int]):
        pulumi.set(self, "metric", value)

    @property
    @pulumi.getter
    def token(self) -> pulumi.Input[str]:
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: pulumi.Input[str]):
        pulumi.set(self, "token", value)

    @property
    @pulumi.getter
    def url(self) -> pulumi.Input[str]:
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: pulumi.Input[str]):
        pulumi.set(self, "url", value)


class ExternalNetwork(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cloudspace_id: Optional[pulumi.Input[str]] = None,
                 customer_id: Optional[pulumi.Input[str]] = None,
                 external_network_id: Optional[pulumi.Input[str]] = None,
                 external_network_ip: Optional[pulumi.Input[str]] = None,
                 external_network_type: Optional[pulumi.Input[str]] = None,
                 metric: Optional[pulumi.Input[int]] = None,
                 token: Optional[pulumi.Input[str]] = None,
                 url: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a ExternalNetwork resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ExternalNetworkArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ExternalNetwork resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ExternalNetworkArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ExternalNetworkArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cloudspace_id: Optional[pulumi.Input[str]] = None,
                 customer_id: Optional[pulumi.Input[str]] = None,
                 external_network_id: Optional[pulumi.Input[str]] = None,
                 external_network_ip: Optional[pulumi.Input[str]] = None,
                 external_network_type: Optional[pulumi.Input[str]] = None,
                 metric: Optional[pulumi.Input[int]] = None,
                 token: Optional[pulumi.Input[str]] = None,
                 url: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ExternalNetworkArgs.__new__(ExternalNetworkArgs)

            if cloudspace_id is None and not opts.urn:
                raise TypeError("Missing required property 'cloudspace_id'")
            __props__.__dict__["cloudspace_id"] = cloudspace_id
            if customer_id is None and not opts.urn:
                raise TypeError("Missing required property 'customer_id'")
            __props__.__dict__["customer_id"] = None if customer_id is None else pulumi.Output.secret(customer_id)
            if external_network_id is None and not opts.urn:
                raise TypeError("Missing required property 'external_network_id'")
            __props__.__dict__["external_network_id"] = external_network_id
            if external_network_ip is None and not opts.urn:
                raise TypeError("Missing required property 'external_network_ip'")
            __props__.__dict__["external_network_ip"] = external_network_ip
            if external_network_type is None and not opts.urn:
                raise TypeError("Missing required property 'external_network_type'")
            __props__.__dict__["external_network_type"] = external_network_type
            if metric is None and not opts.urn:
                raise TypeError("Missing required property 'metric'")
            __props__.__dict__["metric"] = metric
            if token is None and not opts.urn:
                raise TypeError("Missing required property 'token'")
            __props__.__dict__["token"] = None if token is None else pulumi.Output.secret(token)
            if url is None and not opts.urn:
                raise TypeError("Missing required property 'url'")
            __props__.__dict__["url"] = None if url is None else pulumi.Output.secret(url)
        super(ExternalNetwork, __self__).__init__(
            'vco:cloudspace:ExternalNetwork',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'ExternalNetwork':
        """
        Get an existing ExternalNetwork resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ExternalNetworkArgs.__new__(ExternalNetworkArgs)

        __props__.__dict__["cloudspace_id"] = None
        __props__.__dict__["customer_id"] = None
        __props__.__dict__["external_network_id"] = None
        __props__.__dict__["external_network_ip"] = None
        __props__.__dict__["external_network_type"] = None
        __props__.__dict__["metric"] = None
        __props__.__dict__["token"] = None
        __props__.__dict__["url"] = None
        return ExternalNetwork(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def cloudspace_id(self) -> pulumi.Output[str]:
        return pulumi.get(self, "cloudspace_id")

    @property
    @pulumi.getter(name="customerID")
    def customer_id(self) -> pulumi.Output[str]:
        return pulumi.get(self, "customer_id")

    @property
    @pulumi.getter
    def external_network_id(self) -> pulumi.Output[str]:
        return pulumi.get(self, "external_network_id")

    @property
    @pulumi.getter
    def external_network_ip(self) -> pulumi.Output[str]:
        return pulumi.get(self, "external_network_ip")

    @property
    @pulumi.getter
    def external_network_type(self) -> pulumi.Output[str]:
        return pulumi.get(self, "external_network_type")

    @property
    @pulumi.getter
    def metric(self) -> pulumi.Output[int]:
        return pulumi.get(self, "metric")

    @property
    @pulumi.getter
    def token(self) -> pulumi.Output[str]:
        return pulumi.get(self, "token")

    @property
    @pulumi.getter
    def url(self) -> pulumi.Output[str]:
        return pulumi.get(self, "url")

