# Generated by Django 2.2.24 on 2021-10-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_hubl_landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generalcontact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='joincontact',
            options={},
        ),
    ]
