# Generated by Django 2.2.24 on 2021-10-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_hubl_landing', '0002_auto_20211022_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ville'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='companyname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name="nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='distancial',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='travail à distance'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='firstname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='prénom'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='téléphone'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='price',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Budget ou TJM'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='role',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='rôle'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='startdate',
            field=models.DateField(blank=True, null=True, verbose_name='Date de démarrage'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Description de la mission'),
        ),
    ]
