# Generated by Django 2.2.24 on 2021-10-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_hubl_landing', '0004_remove_clientcontact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='joincontact',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='nom'),
        ),
    ]
