# Generated by Django 2.2.24 on 2021-10-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_hubl_landing', '0005_auto_20211024_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Network',
        ),
    ]
