
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-31T15:11:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0da0a559ff704008be7344fe9775fd052202d246",
 "version": "0.17.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
