
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-03T01:06:56+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9b6b574a954daeb4ee2d8fb2159e52d1a9af4e4",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
