# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dydxprotocol/perpetuals/tx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from dydxprotocol.perpetuals import perpetual_pb2 as dydxprotocol_dot_perpetuals_dot_perpetual__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n dydxprotocol/perpetuals/tx.proto\x12\x17\x64ydxprotocol.perpetuals\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x14gogoproto/gogo.proto\x1a\'dydxprotocol/perpetuals/perpetual.proto\"\x8b\x01\n\x12MsgCreatePerpetual\x12+\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressString\x12\x38\n\x06params\x18\x02 \x01(\x0b\x32(.dydxprotocol.perpetuals.PerpetualParams:\x0e\x82\xe7\xb0*\tauthority\"\x1c\n\x1aMsgCreatePerpetualResponse\";\n\x0e\x46undingPremium\x12\x14\n\x0cperpetual_id\x18\x01 \x01(\r\x12\x13\n\x0bpremium_ppm\x18\x02 \x01(\x05\"R\n\x12MsgAddPremiumVotes\x12<\n\x05votes\x18\x01 \x03(\x0b\x32\'.dydxprotocol.perpetuals.FundingPremiumB\x04\xc8\xde\x1f\x00\"\x1c\n\x1aMsgAddPremiumVotesResponse2\xef\x01\n\x03Msg\x12s\n\x0f\x41\x64\x64PremiumVotes\x12+.dydxprotocol.perpetuals.MsgAddPremiumVotes\x1a\x33.dydxprotocol.perpetuals.MsgAddPremiumVotesResponse\x12s\n\x0f\x43reatePerpetual\x12+.dydxprotocol.perpetuals.MsgCreatePerpetual\x1a\x33.dydxprotocol.perpetuals.MsgCreatePerpetualResponseB>Z<github.com/dydxprotocol/v4-chain/protocol/x/perpetuals/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dydxprotocol.perpetuals.tx_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z<github.com/dydxprotocol/v4-chain/protocol/x/perpetuals/types'
  _MSGCREATEPERPETUAL.fields_by_name['authority']._options = None
  _MSGCREATEPERPETUAL.fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _MSGCREATEPERPETUAL._options = None
  _MSGCREATEPERPETUAL._serialized_options = b'\202\347\260*\tauthority'
  _MSGADDPREMIUMVOTES.fields_by_name['votes']._options = None
  _MSGADDPREMIUMVOTES.fields_by_name['votes']._serialized_options = b'\310\336\037\000'
  _globals['_MSGCREATEPERPETUAL']._serialized_start=177
  _globals['_MSGCREATEPERPETUAL']._serialized_end=316
  _globals['_MSGCREATEPERPETUALRESPONSE']._serialized_start=318
  _globals['_MSGCREATEPERPETUALRESPONSE']._serialized_end=346
  _globals['_FUNDINGPREMIUM']._serialized_start=348
  _globals['_FUNDINGPREMIUM']._serialized_end=407
  _globals['_MSGADDPREMIUMVOTES']._serialized_start=409
  _globals['_MSGADDPREMIUMVOTES']._serialized_end=491
  _globals['_MSGADDPREMIUMVOTESRESPONSE']._serialized_start=493
  _globals['_MSGADDPREMIUMVOTESRESPONSE']._serialized_end=521
  _globals['_MSG']._serialized_start=524
  _globals['_MSG']._serialized_end=763
# @@protoc_insertion_point(module_scope)
