# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.03-sp1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200100_virtual_networks import InlineResponse200100VirtualNetworks  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200100VirtualNetworks(unittest.TestCase):
    """InlineResponse200100VirtualNetworks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200100VirtualNetworks(self):
        """Test InlineResponse200100VirtualNetworks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200100_virtual_networks.InlineResponse200100VirtualNetworks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
