
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-30T15:58:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8221c3e0bbc114f7346801256d1628edb390129",
 "version": "0.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
