# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('aci')


class _ExportableConfig(types.ModuleType):
    @property
    def insecure(self) -> Optional[bool]:
        """
        Allow insecure HTTPS client. This can also be set as the ACI_INSECURE environment variable. Defaults to true.
        """
        return __config__.get_bool('insecure')

    @property
    def logging(self) -> Optional[bool]:
        """
        Enable debug logging. This can also be set as the ACI_LOGGING environment variable. Defaults to false.
        """
        return __config__.get_bool('logging')

    @property
    def password(self) -> str:
        """
        Password for the APIC Account. This can also be set as the ACI_PASSWORD environment variable.
        """
        return __config__.get('password') or (_utilities.get_env('ACI_PASSWORD') or '')

    @property
    def retries(self) -> Optional[int]:
        """
        Number of retries for REST API calls. This can also be set as the ACI_RETRIES environment variable. Defaults to 3.
        """
        return __config__.get_int('retries')

    @property
    def url(self) -> str:
        """
        URL of the Cisco APIC web interface. This can also be set as the ACI_URL environment variable.
        """
        return __config__.get('url') or (_utilities.get_env('ACI_URL') or '')

    @property
    def username(self) -> str:
        """
        Username for the APIC Account. This can also be set as the ACI_USERNAME environment variable.
        """
        return __config__.get('username') or (_utilities.get_env('ACI_USERNAME') or '')

