# Generated by Django 3.0.13 on 2022-01-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='answer',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Answer'),
        ),
    ]
