#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2304-74-g0043eee0"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2304
#define NETGEN_VERSION_TWEAK 74
#define NETGEN_VERSION_HASH "g0043eee0"
#endif // NETGEN_VERSION_HPP_INCLUDED
