# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechly/slu/v2beta1/batch_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from speechly.slu.v2beta1 import batch_pb2 as speechly_dot_slu_dot_v2beta1_dot_batch__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$speechly/slu/v2beta1/batch_api.proto\x12\x14speechly.slu.v2beta1\x1a speechly/slu/v2beta1/batch.proto\"\x9f\x01\n\x19ProcessAudioSourceRequest\x12=\n\x06\x63onfig\x18\x01 \x01(\x0b\x32-.speechly.slu.v2beta1.ProcessAudioBatchConfig\x12\x43\n\x06source\x18\x02 \x03(\x0b\x32\x33.speechly.slu.v2beta1.ProcessAudioSourceRequestItem\"P\n\x1aProcessAudioSourceResponse\x12\x32\n\toperation\x18\x01 \x03(\x0b\x32\x1f.speechly.slu.v2beta1.Operation\"t\n\x12QueryStatusRequest\x12\x15\n\roperation_ids\x18\x01 \x03(\t\x12\x1c\n\x14operation_references\x18\x02 \x03(\t\x12\x10\n\x08\x62\x61tch_id\x18\x03 \x01(\t\x12\x17\n\x0f\x62\x61tch_reference\x18\x04 \x01(\t\"I\n\x13QueryStatusResponse\x12\x32\n\toperation\x18\x01 \x03(\x0b\x32\x1f.speechly.slu.v2beta1.Operation2\xe7\x01\n\x08\x42\x61tchAPI\x12w\n\x12ProcessAudioSource\x12/.speechly.slu.v2beta1.ProcessAudioSourceRequest\x1a\x30.speechly.slu.v2beta1.ProcessAudioSourceResponse\x12\x62\n\x0bQueryStatus\x12(.speechly.slu.v2beta1.QueryStatusRequest\x1a).speechly.slu.v2beta1.QueryStatusResponseB\x80\x01\n\x18\x63om.speechly.slu.v2beta1B\rBatchApiProtoP\x01Z\x1fspeechly/slu/v2beta1;sluv2beta1\xa2\x02\x03SSX\xaa\x02\x14Speechly.Slu.V2Beta1\xca\x02\x14Speechly\\Slu\\V2Beta1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speechly.slu.v2beta1.batch_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.speechly.slu.v2beta1B\rBatchApiProtoP\001Z\037speechly/slu/v2beta1;sluv2beta1\242\002\003SSX\252\002\024Speechly.Slu.V2Beta1\312\002\024Speechly\\Slu\\V2Beta1'
  _globals['_PROCESSAUDIOSOURCEREQUEST']._serialized_start=97
  _globals['_PROCESSAUDIOSOURCEREQUEST']._serialized_end=256
  _globals['_PROCESSAUDIOSOURCERESPONSE']._serialized_start=258
  _globals['_PROCESSAUDIOSOURCERESPONSE']._serialized_end=338
  _globals['_QUERYSTATUSREQUEST']._serialized_start=340
  _globals['_QUERYSTATUSREQUEST']._serialized_end=456
  _globals['_QUERYSTATUSRESPONSE']._serialized_start=458
  _globals['_QUERYSTATUSRESPONSE']._serialized_end=531
  _globals['_BATCHAPI']._serialized_start=534
  _globals['_BATCHAPI']._serialized_end=765
# @@protoc_insertion_point(module_scope)
