
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-31T13:47:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd2ef2bb65cc1316fd04fd231af5a652f2667dab",
 "version": "1.0.0a14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
