
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-31T10:35:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f093438cdc663f3dd9c3d420171b34480aa6034a",
 "version": "1.0.15.post.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
