# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from speechly.analytics.v1 import analytics_api_pb2 as speechly_dot_analytics_dot_v1_dot_analytics__api__pb2


class AnalyticsAPIStub(object):
  """Speechly Analytics API contains methods to get accumulated access data
  for given apps and/or projects.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UtteranceStatistics = channel.unary_unary(
        '/speechly.analytics.v1.AnalyticsAPI/UtteranceStatistics',
        request_serializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.UtteranceStatisticsRequest.SerializeToString,
        response_deserializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.UtteranceStatisticsResponse.FromString,
        )
    self.Utterances = channel.unary_unary(
        '/speechly.analytics.v1.AnalyticsAPI/Utterances',
        request_serializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.UtterancesRequest.SerializeToString,
        response_deserializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.UtterancesResponse.FromString,
        )
    self.RegisterUtterance = channel.unary_unary(
        '/speechly.analytics.v1.AnalyticsAPI/RegisterUtterance',
        request_serializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.RegisterUtteranceRequest.SerializeToString,
        response_deserializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.RegisterUtteranceResponse.FromString,
        )
    self.RegisterUtterances = channel.unary_unary(
        '/speechly.analytics.v1.AnalyticsAPI/RegisterUtterances',
        request_serializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.RegisterUtterancesRequest.SerializeToString,
        response_deserializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.RegisterUtterancesResponse.FromString,
        )
    self.ModerationStatistics = channel.unary_unary(
        '/speechly.analytics.v1.AnalyticsAPI/ModerationStatistics',
        request_serializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.ModerationStatisticsRequest.SerializeToString,
        response_deserializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.ModerationStatisticsResponse.FromString,
        )
    self.UserStatistics = channel.unary_unary(
        '/speechly.analytics.v1.AnalyticsAPI/UserStatistics',
        request_serializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.UserStatisticsRequest.SerializeToString,
        response_deserializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.UserStatisticsResponse.FromString,
        )


class AnalyticsAPIServicer(object):
  """Speechly Analytics API contains methods to get accumulated access data
  for given apps and/or projects.
  """

  def UtteranceStatistics(self, request, context):
    """Get a summary of utterances for a given time period.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Utterances(self, request, context):
    """Get a sample of recent utterances.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterUtterance(self, request, context):
    """Register a data point of an on-device or on-premise utterance.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterUtterances(self, request, context):
    """Register multiple utterances in a single request.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ModerationStatistics(self, request, context):
    """Get moderation event statistics for a project.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserStatistics(self, request, context):
    """Get statistics about user behaviour.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AnalyticsAPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UtteranceStatistics': grpc.unary_unary_rpc_method_handler(
          servicer.UtteranceStatistics,
          request_deserializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.UtteranceStatisticsRequest.FromString,
          response_serializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.UtteranceStatisticsResponse.SerializeToString,
      ),
      'Utterances': grpc.unary_unary_rpc_method_handler(
          servicer.Utterances,
          request_deserializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.UtterancesRequest.FromString,
          response_serializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.UtterancesResponse.SerializeToString,
      ),
      'RegisterUtterance': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterUtterance,
          request_deserializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.RegisterUtteranceRequest.FromString,
          response_serializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.RegisterUtteranceResponse.SerializeToString,
      ),
      'RegisterUtterances': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterUtterances,
          request_deserializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.RegisterUtterancesRequest.FromString,
          response_serializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.RegisterUtterancesResponse.SerializeToString,
      ),
      'ModerationStatistics': grpc.unary_unary_rpc_method_handler(
          servicer.ModerationStatistics,
          request_deserializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.ModerationStatisticsRequest.FromString,
          response_serializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.ModerationStatisticsResponse.SerializeToString,
      ),
      'UserStatistics': grpc.unary_unary_rpc_method_handler(
          servicer.UserStatistics,
          request_deserializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.UserStatisticsRequest.FromString,
          response_serializer=speechly_dot_analytics_dot_v1_dot_analytics__api__pb2.UserStatisticsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'speechly.analytics.v1.AnalyticsAPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
