# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_aci.apic as __apic
    apic = __apic
    import pulumi_aci.config as __config
    config = __config
else:
    apic = _utilities.lazy_import('pulumi_aci.apic')
    config = _utilities.lazy_import('pulumi_aci.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "aci",
  "mod": "apic",
  "fqn": "pulumi_aci.apic",
  "classes": {
   "aci:apic:Rest": "Rest"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "aci",
  "token": "pulumi:providers:aci",
  "fqn": "pulumi_aci",
  "class": "Provider"
 }
]
"""
)
