
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-31T11:02:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "28633ae1b6ed79f8f70448c99475198a5fe3bcae",
 "version": "1.0.0a12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
