
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-31T15:41:45+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb18cd8869b437ca1a0cdea1394b17e507dd4e48",
 "version": "1.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
