
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-31T10:11:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e3eadde84447b3fc6b252210595fce7bdbba72d5",
 "version": "1.0.0a10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
