# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechly/config/v1/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1espeechly/config/v1/model.proto\x12\x12speechly.config.v1\"j\n\tBaseModel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x61lias\x18\x02 \x01(\t\x12\x17\n\x0fis_downloadable\x18\x03 \x01(\x08\x12\x15\n\ris_streamable\x18\x04 \x01(\x08\x12\x10\n\x08language\x18\x05 \x01(\tBs\n\x16\x63om.speechly.config.v1B\nModelProtoP\x01Z\x1bspeechly/config/v1;configv1\xa2\x02\x03SCX\xaa\x02\x12Speechly.Config.V1\xca\x02\x12Speechly\\Config\\V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speechly.config.v1.model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.speechly.config.v1B\nModelProtoP\001Z\033speechly/config/v1;configv1\242\002\003SCX\252\002\022Speechly.Config.V1\312\002\022Speechly\\Config\\V1'
  _globals['_BASEMODEL']._serialized_start=54
  _globals['_BASEMODEL']._serialized_end=160
# @@protoc_insertion_point(module_scope)
