# Generated by Django 3.2.18 on 2023-06-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snomed_ct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexmaprefset',
            name='map_advice',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='complexmaprefset',
            name='map_rule',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='complexmaprefset',
            name='map_target',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='icd10_mapping',
            name='map_advice',
            field=models.TextField(db_column='mapAdvice', default=''),
        ),
        migrations.AlterField(
            model_name='icd10_mapping',
            name='map_category_name',
            field=models.TextField(db_column='mapCategoryName', default=''),
        ),
        migrations.AlterField(
            model_name='icd10_mapping',
            name='map_rule',
            field=models.TextField(db_column='mapRule', default=''),
        ),
        migrations.AlterField(
            model_name='icd10_mapping',
            name='map_target',
            field=models.TextField(db_column='mapTarget', default=''),
        ),
        migrations.AlterField(
            model_name='icd10_mapping',
            name='map_target_name',
            field=models.TextField(db_column='mapTargetName', db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='icd10_mapping',
            name='referenced_component_name',
            field=models.TextField(db_column='referencedComponentName', default=''),
        ),
    ]
