# -*- coding: utf-8 -*-

"""
    greenbyteapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from greenbyteapi.api_helper import APIHelper

class PredictStatusDismissed(object):

    """Implementation of the 'PredictStatusDismissed' model.

    Status info for a dismissed Predict alert.

    Attributes:
        timestamp_dismissed (datetime): When the alert was dismissed.
        dismissed_by (string): The user who dismissed the alert

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "timestamp_dismissed":'timestampDismissed',
        "dismissed_by":'dismissedBy'
    }

    def __init__(self,
                 timestamp_dismissed=None,
                 dismissed_by=None):
        """Constructor for the PredictStatusDismissed class"""

        # Initialize members of the class
        self.timestamp_dismissed = APIHelper.RFC3339DateTime(timestamp_dismissed) if timestamp_dismissed else None
        self.dismissed_by = dismissed_by


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        timestamp_dismissed = APIHelper.RFC3339DateTime.from_value(dictionary.get("timestampDismissed")).datetime if dictionary.get("timestampDismissed") else None
        dismissed_by = dictionary.get('dismissedBy')

        # Return an object of this model
        return cls(timestamp_dismissed,
                   dismissed_by)


