# -*- coding: utf-8 -*-

"""
    greenbyteapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class PredictSeverityEnum(object):

    """Implementation of the 'PredictSeverity' enum.

    The severity of a Predict alert.

    Attributes:
        HIGH: TODO: type description here.
        LOW: TODO: type description here.

    """

    HIGH = 'high'

    LOW = 'low'

