# -*- coding: utf-8 -*-

"""
    greenbyteapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from greenbyteapi.api_helper import APIHelper

class PredictComment(object):

    """Implementation of the 'PredictComment' model.

    A comment on a Predict alert.

    Attributes:
        user_name (string): TODO: type description here.
        text (string): TODO: type description here.
        timestamp (datetime): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "user_name":'userName',
        "text":'text',
        "timestamp":'timestamp'
    }

    def __init__(self,
                 user_name=None,
                 text=None,
                 timestamp=None):
        """Constructor for the PredictComment class"""

        # Initialize members of the class
        self.user_name = user_name
        self.text = text
        self.timestamp = APIHelper.RFC3339DateTime(timestamp) if timestamp else None


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        user_name = dictionary.get('userName')
        text = dictionary.get('text')
        timestamp = APIHelper.RFC3339DateTime.from_value(dictionary.get("timestamp")).datetime if dictionary.get("timestamp") else None

        # Return an object of this model
        return cls(user_name,
                   text,
                   timestamp)


