# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechly/config/v1/model_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from speechly.config.v1 import model_pb2 as speechly_dot_config_dot_v1_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"speechly/config/v1/model_api.proto\x12\x12speechly.config.v1\x1a\x1espeechly/config/v1/model.proto\"\xa1\x02\n\x14\x44ownloadModelRequest\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\x11\n\tconfig_id\x18\x02 \x01(\t\x12V\n\x12model_architecture\x18\x03 \x01(\x0e\x32:.speechly.config.v1.DownloadModelRequest.ModelArchitecture\"\x8d\x01\n\x11ModelArchitecture\x12\x1e\n\x1aMODEL_ARCHITECTURE_INVALID\x10\x00\x12\x1a\n\x16MODEL_ARCHITECTURE_ORT\x10\x01\x12\x1d\n\x19MODEL_ARCHITECTURE_COREML\x10\x02\x12\x1d\n\x19MODEL_ARCHITECTURE_TFLITE\x10\x03\"&\n\x15\x44ownloadModelResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"=\n\x15ListBaseModelsRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"F\n\x16ListBaseModelsResponse\x12,\n\x05model\x18\x01 \x03(\x0b\x32\x1d.speechly.config.v1.BaseModel\"\x16\n\x14ListLanguagesRequest\"\x86\x01\n\x15ListLanguagesResponse\x12\x45\n\tlanguages\x18\x01 \x03(\x0b\x32\x32.speechly.config.v1.ListLanguagesResponse.Language\x1a&\n\x08Language\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2\xc1\x02\n\x08ModelAPI\x12\x66\n\rDownloadModel\x12(.speechly.config.v1.DownloadModelRequest\x1a).speechly.config.v1.DownloadModelResponse0\x01\x12g\n\x0eListBaseModels\x12).speechly.config.v1.ListBaseModelsRequest\x1a*.speechly.config.v1.ListBaseModelsResponse\x12\x64\n\rListLanguages\x12(.speechly.config.v1.ListLanguagesRequest\x1a).speechly.config.v1.ListLanguagesResponseBv\n\x16\x63om.speechly.config.v1B\rModelApiProtoP\x01Z\x1bspeechly/config/v1;configv1\xa2\x02\x03SCX\xaa\x02\x12Speechly.Config.V1\xca\x02\x12Speechly\\Config\\V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speechly.config.v1.model_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.speechly.config.v1B\rModelApiProtoP\001Z\033speechly/config/v1;configv1\242\002\003SCX\252\002\022Speechly.Config.V1\312\002\022Speechly\\Config\\V1'
  _globals['_DOWNLOADMODELREQUEST']._serialized_start=91
  _globals['_DOWNLOADMODELREQUEST']._serialized_end=380
  _globals['_DOWNLOADMODELREQUEST_MODELARCHITECTURE']._serialized_start=239
  _globals['_DOWNLOADMODELREQUEST_MODELARCHITECTURE']._serialized_end=380
  _globals['_DOWNLOADMODELRESPONSE']._serialized_start=382
  _globals['_DOWNLOADMODELRESPONSE']._serialized_end=420
  _globals['_LISTBASEMODELSREQUEST']._serialized_start=422
  _globals['_LISTBASEMODELSREQUEST']._serialized_end=483
  _globals['_LISTBASEMODELSRESPONSE']._serialized_start=485
  _globals['_LISTBASEMODELSRESPONSE']._serialized_end=555
  _globals['_LISTLANGUAGESREQUEST']._serialized_start=557
  _globals['_LISTLANGUAGESREQUEST']._serialized_end=579
  _globals['_LISTLANGUAGESRESPONSE']._serialized_start=582
  _globals['_LISTLANGUAGESRESPONSE']._serialized_end=716
  _globals['_LISTLANGUAGESRESPONSE_LANGUAGE']._serialized_start=678
  _globals['_LISTLANGUAGESRESPONSE_LANGUAGE']._serialized_end=716
  _globals['_MODELAPI']._serialized_start=719
  _globals['_MODELAPI']._serialized_end=1040
# @@protoc_insertion_point(module_scope)
