# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechly/identity/v2/identity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#speechly/identity/v2/identity.proto\x12\x14speechly.identity.v2\"5\n\x10\x41pplicationScope\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\x11\n\tconfig_id\x18\x03 \x01(\t\"\"\n\x0cProjectScope\x12\x12\n\nproject_id\x18\x01 \x01(\tB\x80\x01\n\x18\x63om.speechly.identity.v2B\rIdentityProtoP\x01Z\x1fspeechly/identity/v2;identityv2\xa2\x02\x03SIX\xaa\x02\x14Speechly.Identity.V2\xca\x02\x14Speechly\\Identity\\V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speechly.identity.v2.identity_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.speechly.identity.v2B\rIdentityProtoP\001Z\037speechly/identity/v2;identityv2\242\002\003SIX\252\002\024Speechly.Identity.V2\312\002\024Speechly\\Identity\\V2'
  _globals['_APPLICATIONSCOPE']._serialized_start=61
  _globals['_APPLICATIONSCOPE']._serialized_end=114
  _globals['_PROJECTSCOPE']._serialized_start=116
  _globals['_PROJECTSCOPE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
