"""
Illuminants module provides various illuminant spectral data.
"""

from sentinel_toolkit.colorimetry.illuminants.d65 import D65_360_830_1NM
from sentinel_toolkit.colorimetry.illuminants.illuminants import WELL_KNOWN_ILLUMINANTS
from sentinel_toolkit.colorimetry.illuminants.illuminants import get_well_known_illuminant
from sentinel_toolkit.colorimetry.illuminants.illuminants import get_illuminant_from_file
from sentinel_toolkit.colorimetry.illuminants.illuminants import get_illuminant_in_range
from sentinel_toolkit.colorimetry.illuminants.illuminants import get_well_known_illuminant_names
