# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechly/moderation/v1beta1/moderation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,speechly/moderation/v1beta1/moderation.proto\x12\x1bspeechly.moderation.v1beta1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n\x10\x44iscourseContext\x12\x12\n\nchannel_id\x18\x01 \x01(\t\x12\x12\n\nspeaker_id\x18\x02 \x01(\t\x12\x14\n\x0clistener_ids\x18\x03 \x03(\t\x12.\n\nstart_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"@\n\x0fModerationLabel\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0f\n\x07\x66lagged\x18\x03 \x01(\x08\"\x8a\x01\n\x15\x41udioModerationConfig\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x15\n\rlanguage_code\x18\x02 \x01(\t\x12H\n\x11\x64iscourse_context\x18\x03 \x01(\x0b\x32-.speechly.moderation.v1beta1.DiscourseContext\"\x96\x01\n\x11ModerationSegment\x12\r\n\x05index\x18\x01 \x01(\r\x12\x12\n\ntranscript\x18\x02 \x01(\t\x12<\n\x06labels\x18\x03 \x03(\x0b\x32,.speechly.moderation.v1beta1.ModerationLabel\x12\x10\n\x08start_ms\x18\x04 \x01(\r\x12\x0e\n\x06\x65nd_ms\x18\x05 \x01(\rB\x9e\x01\n\x1f\x63om.speechly.moderation.v1beta1B\x0fModerationProtoP\x01Z&speechly/moderation/v1beta1;sluv1beta1\xa2\x02\x03SMX\xaa\x02\x1bSpeechly.Moderation.V1Beta1\xca\x02\x1bSpeechly\\Moderation\\V1Beta1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speechly.moderation.v1beta1.moderation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037com.speechly.moderation.v1beta1B\017ModerationProtoP\001Z&speechly/moderation/v1beta1;sluv1beta1\242\002\003SMX\252\002\033Speechly.Moderation.V1Beta1\312\002\033Speechly\\Moderation\\V1Beta1'
  _globals['_DISCOURSECONTEXT']._serialized_start=111
  _globals['_DISCOURSECONTEXT']._serialized_end=285
  _globals['_MODERATIONLABEL']._serialized_start=287
  _globals['_MODERATIONLABEL']._serialized_end=351
  _globals['_AUDIOMODERATIONCONFIG']._serialized_start=354
  _globals['_AUDIOMODERATIONCONFIG']._serialized_end=492
  _globals['_MODERATIONSEGMENT']._serialized_start=495
  _globals['_MODERATIONSEGMENT']._serialized_end=645
# @@protoc_insertion_point(module_scope)
