
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-30T13:47:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6e48278ec21a58c21034ce3748d8b5f2b75d68f",
 "version": "0.13.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
