
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-16T10:37:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dafef97fe4fd1f2f713ef1e3503d6b13b20c1c1f",
 "version": "1.9.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
