# Generated by Django 2.2.24 on 2021-10-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_hubl_landing', '0003_auto_20211022_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontact',
            name='name',
        ),
    ]
