# Generated by Django 2.2.24 on 2021-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_hubl_landing', '0006_auto_20211029_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='joincontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='téléphone'),
        ),
    ]
