# Generated by Django 2.2.24 on 2021-11-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_hubl_landing', '0007_joincontact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Durée de la mission'),
        ),
    ]
