
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-01T18:27:22+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "cdab5141bbba54442d1d04bfeb9de2eec8181028",
 "version": "1.3.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
