#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2304-61-gc8888086"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2304
#define NETGEN_VERSION_TWEAK 61
#define NETGEN_VERSION_HASH "gc8888086"
#endif // NETGEN_VERSION_HPP_INCLUDED
